import csv
import zipfile
from contextlib import closing
from dataclasses import dataclass
from io import BytesIO, StringIO
from pathlib import PurePosixPath

from docx import Document
from openpyxl import load_workbook
from pptx import Presentation
from pypdf import PdfReader

from app.config import settings
from app.services.document.document_operation_registry import DocumentType, Fidelity
from app.services.document.extraction_models import ExtractedDocument, ExtractionMode


@dataclass(frozen=True)
class FidelityAssessment:
    fidelity: Fidelity
    note: str | None = None


class GeneratedDocumentValidationError(ValueError):
    pass


class DocumentValidationService:
    """Reopen generated bytes with the matching parser before they are stored."""

    _OOXML_TYPES = frozenset({DocumentType.DOCX, DocumentType.XLSX, DocumentType.PPTX})
    _OOXML_REQUIRED_PARTS = {
        DocumentType.DOCX: "word/document.xml",
        DocumentType.XLSX: "xl/workbook.xml",
        DocumentType.PPTX: "ppt/presentation.xml",
    }
    _UNSAFE_XML_MARKERS = (b"<!DOCTYPE", b"<!ENTITY")
    _MALFORMED_MESSAGE = "The file is too large or malformed (or corrupt)."

    def __init__(
        self,
        *,
        ooxml_max_uncompressed_bytes: int | None = None,
        ooxml_max_total_ratio: int | None = None,
        ooxml_max_entry_ratio: int | None = None,
        ooxml_max_entries: int | None = None,
    ) -> None:
        self.ooxml_max_uncompressed_bytes = (
            ooxml_max_uncompressed_bytes
            if ooxml_max_uncompressed_bytes is not None
            else settings.DOCUMENT_OOXML_MAX_UNCOMPRESSED_BYTES
        )
        self.ooxml_max_total_ratio = (
            ooxml_max_total_ratio
            if ooxml_max_total_ratio is not None
            else settings.DOCUMENT_OOXML_MAX_TOTAL_RATIO
        )
        self.ooxml_max_entry_ratio = (
            ooxml_max_entry_ratio
            if ooxml_max_entry_ratio is not None
            else settings.DOCUMENT_OOXML_MAX_ENTRY_RATIO
        )
        self.ooxml_max_entries = (
            ooxml_max_entries
            if ooxml_max_entries is not None
            else settings.DOCUMENT_OOXML_MAX_ENTRIES
        )

    def validate(self, file_data: bytes, document_type: DocumentType) -> None:
        if not file_data:
            raise GeneratedDocumentValidationError("The generated document is empty.")
        try:
            if document_type == DocumentType.PDF:
                self._validate_generated_signature(file_data, document_type)
                if len(PdfReader(BytesIO(file_data)).pages) < 1:
                    raise GeneratedDocumentValidationError(
                        "The generated PDF does not contain any pages."
                    )
            elif document_type == DocumentType.DOCX:
                self._validate_generated_signature(file_data, document_type)
                Document(BytesIO(file_data))
            elif document_type == DocumentType.XLSX:
                self._validate_generated_signature(file_data, document_type)
                with closing(load_workbook(BytesIO(file_data), read_only=True)) as workbook:
                    if not workbook.sheetnames:
                        raise GeneratedDocumentValidationError(
                            "The generated Excel workbook does not contain a worksheet."
                        )
            elif document_type == DocumentType.CSV:
                text = self._decode(file_data)
                if not any(row for row in csv.reader(StringIO(text))):
                    raise GeneratedDocumentValidationError(
                        "The generated CSV does not contain any rows."
                    )
            elif document_type == DocumentType.PPTX:
                self._validate_generated_signature(file_data, document_type)
                if len(Presentation(BytesIO(file_data)).slides) < 1:
                    raise GeneratedDocumentValidationError(
                        "The generated PowerPoint does not contain any slides."
                    )
            elif document_type in {DocumentType.TXT, DocumentType.MARKDOWN}:
                if not self._decode(file_data).strip():
                    raise GeneratedDocumentValidationError("The generated text document is empty.")
            else:
                raise GeneratedDocumentValidationError(
                    f"Unsupported generated document type: {document_type.value}."
                )
        except GeneratedDocumentValidationError:
            raise
        except Exception as error:
            raise GeneratedDocumentValidationError(
                f"The generated {document_type.value.upper()} document could not be reopened."
            ) from error

    def validate_file_signature(self, file_data: bytes, document_type: DocumentType) -> None:
        if document_type == DocumentType.PDF:
            if b"%PDF-" not in file_data[:1024]:
                raise GeneratedDocumentValidationError(self._MALFORMED_MESSAGE)
            return
        if document_type in self._OOXML_TYPES:
            self.validate_ooxml_container(file_data, document_type)

    def _validate_generated_signature(self, file_data: bytes, document_type: DocumentType) -> None:
        try:
            self.validate_file_signature(file_data, document_type)
        except GeneratedDocumentValidationError as error:
            raise GeneratedDocumentValidationError(
                f"The generated {document_type.value.upper()} document could not be reopened."
            ) from error

    def validate_ooxml_container(self, file_data: bytes, document_type: DocumentType) -> None:
        """Reject unsafe OOXML archives using metadata checks before XML parsing."""
        if document_type not in self._OOXML_TYPES:
            return
        if not file_data.startswith((b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08")):
            raise GeneratedDocumentValidationError(self._MALFORMED_MESSAGE)

        try:
            with zipfile.ZipFile(BytesIO(file_data)) as archive:
                entries = archive.infolist()
                if not entries or len(entries) > self.ooxml_max_entries:
                    self._reject_ooxml()

                total_limit = min(
                    self.ooxml_max_uncompressed_bytes,
                    len(file_data) * self.ooxml_max_total_ratio,
                )
                total_size = 0
                names: set[str] = set()
                for entry in entries:
                    name = entry.filename
                    if self._unsafe_archive_name(name) or name in names:
                        self._reject_ooxml()
                    names.add(name)
                    if entry.flag_bits & 0x1:
                        self._reject_ooxml()
                    total_size += entry.file_size
                    if total_size > total_limit:
                        self._reject_ooxml()
                    if entry.file_size and (
                        entry.compress_size <= 0
                        or entry.file_size / entry.compress_size > self.ooxml_max_entry_ratio
                    ):
                        self._reject_ooxml()

                required = {
                    "[Content_Types].xml",
                    self._OOXML_REQUIRED_PARTS[document_type],
                }
                if not required.issubset(names):
                    self._reject_ooxml()

                # OOXML readers eventually parse these parts. Inspect them under the same
                # bounded archive limits and prohibit entity/DTD expansion up front.
                for entry in entries:
                    if not entry.filename.casefold().endswith((".xml", ".rels")):
                        continue
                    self._inspect_xml_part(archive, entry, total_limit)
        except GeneratedDocumentValidationError:
            raise
        except (OSError, RuntimeError, zipfile.BadZipFile, zipfile.LargeZipFile) as error:
            raise GeneratedDocumentValidationError(self._MALFORMED_MESSAGE) from error

    def _inspect_xml_part(
        self,
        archive: zipfile.ZipFile,
        entry: zipfile.ZipInfo,
        total_limit: int,
    ) -> None:
        bytes_read = 0
        tail = b""
        with archive.open(entry, "r") as stream:
            while chunk := stream.read(64 * 1024):
                bytes_read += len(chunk)
                if bytes_read > entry.file_size or bytes_read > total_limit:
                    self._reject_ooxml()
                probe = (tail + chunk).upper()
                if any(marker in probe for marker in self._UNSAFE_XML_MARKERS):
                    self._reject_ooxml()
                tail = probe[-16:]

    @staticmethod
    def _unsafe_archive_name(name: str) -> bool:
        if not name or "\\" in name or "//" in name or ":" in name or name.startswith("/"):
            return True
        parts = PurePosixPath(name).parts
        return any(part in {"", ".", ".."} for part in parts)

    def _reject_ooxml(self) -> None:
        raise GeneratedDocumentValidationError(self._MALFORMED_MESSAGE)

    def assess_generation(
        self,
        file_data: bytes,
        document_type: DocumentType,
        *,
        source_text: str | None = None,
    ) -> FidelityAssessment:
        """Validate a rendered file and derive fidelity from the content actually reopened."""
        self.validate(file_data, document_type)
        if document_type in {DocumentType.TXT, DocumentType.MARKDOWN}:
            actual = self._decode(file_data)
            if source_text is not None and actual != source_text:
                raise GeneratedDocumentValidationError(
                    "The generated text did not preserve the requested content."
                )
            return FidelityAssessment(Fidelity.FULL)

        if source_text and document_type in {
            DocumentType.PDF,
            DocumentType.DOCX,
            DocumentType.PPTX,
        }:
            actual = self._visible_text(file_data, document_type)
            if self._word_retention(source_text, actual) < 0.8:
                raise GeneratedDocumentValidationError(
                    "The generated document did not preserve enough requested content."
                )
        return FidelityAssessment(Fidelity.HIGH)

    def assess_conversion(
        self,
        source_data: bytes,
        source_type: DocumentType,
        output_data: bytes,
        output_type: DocumentType,
        *,
        expected: Fidelity,
        limitation: str | None,
    ) -> FidelityAssessment:
        """Verify conversion content/ordering and derive its actual fidelity."""
        self.validate(source_data, source_type)
        self.validate(output_data, output_type)

        if {source_type, output_type} <= {DocumentType.TXT, DocumentType.MARKDOWN}:
            if self._decode(source_data) != self._decode(output_data):
                raise GeneratedDocumentValidationError(
                    "The converted text did not preserve the source content."
                )
            return FidelityAssessment(Fidelity.FULL)

        if (source_type, output_type) in {
            (DocumentType.CSV, DocumentType.XLSX),
            (DocumentType.XLSX, DocumentType.CSV),
        }:
            source_rows = self._tabular_rows(source_data, source_type)
            output_rows = self._tabular_rows(output_data, output_type)
            if source_rows != output_rows:
                raise GeneratedDocumentValidationError(
                    "The converted table did not preserve row order or cell values."
                )
            return FidelityAssessment(expected, limitation)

        if source_type == DocumentType.PDF and output_type == DocumentType.XLSX:
            if not self._tabular_rows(output_data, output_type):
                raise GeneratedDocumentValidationError(
                    "The converted workbook does not contain extracted table data."
                )
            return FidelityAssessment(Fidelity.PARTIAL, limitation)

        source_text = self._visible_text(source_data, source_type)
        output_text = self._visible_text(output_data, output_type)
        if source_text and not output_text:
            raise GeneratedDocumentValidationError(
                "The converted document did not preserve readable source content."
            )
        if source_text and output_text and self._word_retention(source_text, output_text) < 0.55:
            raise GeneratedDocumentValidationError(
                "The converted document did not preserve enough source content."
            )
        return FidelityAssessment(expected, limitation)

    @staticmethod
    def fidelity_for_extraction(document: ExtractedDocument) -> FidelityAssessment:
        if document.extraction_mode == ExtractionMode.FULL and not document.warnings:
            return FidelityAssessment(Fidelity.FULL)
        if document.extraction_mode in {ExtractionMode.OCR, ExtractionMode.MIXED}:
            return FidelityAssessment(
                Fidelity.HIGH,
                "Some content was recovered with OCR and may contain recognition errors.",
            )
        if document.extraction_mode == ExtractionMode.TRUNCATED:
            return FidelityAssessment(
                Fidelity.PARTIAL,
                "Only part of the document content was available for this result.",
            )
        return FidelityAssessment(Fidelity.BEST_EFFORT, "Document extraction was incomplete.")

    @staticmethod
    def fidelity_for_verified_modification(document_type: DocumentType) -> FidelityAssessment:
        if document_type == DocumentType.PDF:
            return FidelityAssessment(
                Fidelity.HIGH,
                "PDF page operations preserve pages, but do not re-create editable layout.",
            )
        return FidelityAssessment(Fidelity.FULL)

    def _visible_text(self, file_data: bytes, document_type: DocumentType) -> str:
        if document_type in {DocumentType.TXT, DocumentType.MARKDOWN, DocumentType.CSV}:
            return self._decode(file_data)
        if document_type == DocumentType.PDF:
            return "\n".join(
                (page.extract_text() or "").strip() for page in PdfReader(BytesIO(file_data)).pages
            ).strip()
        if document_type == DocumentType.DOCX:
            document = Document(BytesIO(file_data))
            values = [paragraph.text for paragraph in document.paragraphs]
            values.extend(
                cell.text for table in document.tables for row in table.rows for cell in row.cells
            )
            return "\n".join(values).strip()
        if document_type == DocumentType.XLSX:
            with closing(
                load_workbook(BytesIO(file_data), read_only=True, data_only=False)
            ) as workbook:
                return "\n".join(
                    str(cell.value)
                    for worksheet in workbook.worksheets
                    for row in worksheet.iter_rows()
                    for cell in row
                    if cell.value is not None
                )
        if document_type == DocumentType.PPTX:
            presentation = Presentation(BytesIO(file_data))
            slide_values: list[str] = []
            for slide in presentation.slides:
                for shape in slide.shapes:
                    if getattr(shape, "has_text_frame", False) and shape.text:
                        slide_values.append(shape.text)
                    if getattr(shape, "has_table", False):
                        slide_values.extend(
                            cell.text for row in shape.table.rows for cell in row.cells if cell.text
                        )
            return "\n".join(slide_values)
        return ""

    def _tabular_rows(
        self, file_data: bytes, document_type: DocumentType
    ) -> tuple[tuple[str, ...], ...]:
        if document_type == DocumentType.CSV:
            rows = csv.reader(StringIO(self._decode(file_data)))
            normalized = (self._trim_row(tuple(row)) for row in rows)
            return tuple(row for row in normalized if row)
        with closing(
            load_workbook(BytesIO(file_data), read_only=True, data_only=False)
        ) as workbook:
            worksheet = workbook[workbook.sheetnames[0]]
            normalized = (
                self._trim_row(tuple("" if cell.value is None else str(cell.value) for cell in row))
                for row in worksheet.iter_rows()
            )
            return tuple(row for row in normalized if row)

    @staticmethod
    def _trim_row(row: tuple[str, ...]) -> tuple[str, ...]:
        values = list(row)
        while values and values[-1] == "":
            values.pop()
        return tuple(values)

    @staticmethod
    def _word_retention(source: str, output: str) -> float:
        source_words = [word.casefold() for word in source.split() if word.strip()]
        if not source_words:
            return 1.0
        output_words = {word.casefold() for word in output.split() if word.strip()}
        return sum(word in output_words for word in source_words) / len(source_words)

    @staticmethod
    def _decode(file_data: bytes) -> str:
        try:
            return file_data.decode("utf-8-sig")
        except UnicodeDecodeError as error:
            raise GeneratedDocumentValidationError(
                "The generated text document is not valid UTF-8."
            ) from error
