import csv
from contextlib import closing
from io import BytesIO, StringIO

from docx import Document
from openpyxl import load_workbook
from pptx import Presentation
from pypdf import PdfReader

from app.services.document.document_operation_registry import DocumentType


class GeneratedDocumentValidationError(ValueError):
    pass


class DocumentValidationService:
    """Reopen generated bytes with the matching parser before they are stored."""

    def validate(self, file_data: bytes, document_type: DocumentType) -> None:
        if not file_data:
            raise GeneratedDocumentValidationError("The generated document is empty.")
        try:
            if document_type == DocumentType.PDF:
                if len(PdfReader(BytesIO(file_data)).pages) < 1:
                    raise GeneratedDocumentValidationError(
                        "The generated PDF does not contain any pages."
                    )
            elif document_type == DocumentType.DOCX:
                Document(BytesIO(file_data))
            elif document_type == DocumentType.XLSX:
                with closing(load_workbook(BytesIO(file_data), read_only=True)) as workbook:
                    if not workbook.sheetnames:
                        raise GeneratedDocumentValidationError(
                            "The generated Excel workbook does not contain a worksheet."
                        )
            elif document_type == DocumentType.CSV:
                text = self._decode(file_data)
                if not any(row for row in csv.reader(StringIO(text))):
                    raise GeneratedDocumentValidationError(
                        "The generated CSV does not contain any rows."
                    )
            elif document_type == DocumentType.PPTX:
                if len(Presentation(BytesIO(file_data)).slides) < 1:
                    raise GeneratedDocumentValidationError(
                        "The generated PowerPoint does not contain any slides."
                    )
            elif document_type in {DocumentType.TXT, DocumentType.MARKDOWN}:
                if not self._decode(file_data).strip():
                    raise GeneratedDocumentValidationError("The generated text document is empty.")
            else:
                raise GeneratedDocumentValidationError(
                    f"Unsupported generated document type: {document_type.value}."
                )
        except GeneratedDocumentValidationError:
            raise
        except Exception as error:
            raise GeneratedDocumentValidationError(
                f"The generated {document_type.value.upper()} document could not be reopened."
            ) from error

    @staticmethod
    def _decode(file_data: bytes) -> str:
        try:
            return file_data.decode("utf-8-sig")
        except UnicodeDecodeError as error:
            raise GeneratedDocumentValidationError(
                "The generated text document is not valid UTF-8."
            ) from error
